Closes #97
thinknetica-django-lab-02/realzuy pull request #109
Opened 2021-05-04 10:22 UTC by realzuy

Closes #97

2021-05-04 10:50 UTC, morgangt requested changes

2021-05-04 10:50 UTC, morgangt commented on mymp/mymp/settings.py
> +    dsn="https://b291563fb9d64c3797b68fdc5ded7652@o612908.ingest.sentry.io/5748612",
Надо убрать в settings иначе можно за DDOS твой sentry

2021-05-06 11:26 UTC, morgangt requested changes

2021-05-06 11:26 UTC, morgangt commented on mymp/main/templates/base_mobile.html
> +    </style>
Кажется тут уже достаточно кода чтобы вынести в отдельный css файл 
например в starter-template.css

2021-05-06 11:26 UTC, morgangt commented on mymp/main/templates/base_mobile.html
> +    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
свойства тега integrity можно убирать

2021-05-06 11:26 UTC, morgangt commented on mymp/mymp/settings.py
> +    dsn=config('SENTRY_DSN'),
у вас есть проблема с файлом config если у меня нет файла config то проект не запустится
нужно либо начать использовать значения по-умолчанию config('SENTRY_DSN', default='')
либо создать файл example.config.py и закомитеть его в репозиторий, со списком всех переменных которых нужно заполнить

2021-05-06 11:38 UTC, realzuy commented on mymp/mymp/settings.py
> +    dsn=config('SENTRY_DSN'),
ок

2021-05-06 11:39 UTC, realzuy commented on mymp/main/templates/base_mobile.html
> +    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
вообще не принципиально, давай оставим пока

2021-05-06 11:42 UTC, realzuy commented on mymp/main/templates/base_mobile.html
> +    </style>
в целом да, я убрал в принципе из проекта.

2021-05-06 11:51 UTC, morgangt approved these changes
👌

2021-05-06 11:53 UTC, merged