Closes #38
thinknetica-django-lab-02/realzuy pull request #47
Opened 2021-04-07 14:53 UTC by realzuy

Closes #38

2021-04-08 21:26 UTC, morgangt requested changes
надо убрать пароль и email из кода и перенести их в подключаемый конфиг файл

2021-04-08 21:26 UTC, morgangt commented on mymp/mymp/settings.py
> +EMAIL_HOST_PASSWORD = 'Jhsgoweut^&fdjkJHHF75*'
надо поменять пароль от этого email и убрать пароль из репозитория

2021-04-09 07:49 UTC, realzuy commented on mymp/mymp/settings.py
> +EMAIL_HOST_PASSWORD = 'Jhsgoweut^&fdjkJHHF75*'
вынес в отдельный файл за пределами гита

2021-04-09 15:16 UTC, morgangt commented on .gitignore
> +/mymp/mymp/credentials.py
здесь можно просто указать всю папку игнорировать `mymp`

2021-04-09 15:17 UTC, morgangt approved these changes

2021-04-09 16:10 UTC, merged