Closes #56, Closes #57
thinknetica-django-lab-02/realzuy pull request #63
Opened 2021-04-14 19:16 UTC by realzuy

Closes #56, Closes #57

2021-04-14 23:01 UTC, morgangt requested changes

2021-04-14 23:01 UTC, morgangt commented on mymp/main/tasks.py
> +import main.models as model
чаще всего импортируют конкретную модель 
`from main.models import User, Strategy, Profile`

2021-04-15 07:48 UTC, realzuy commented on mymp/main/tasks.py
> +            SendNewStrategiesMessage(strategies, profile)
это фильтр не на первого пользователя а на первую рассылку. фильтровать по имени рассылки я посчитал неправильным, поэтому фильтр стоит по номеру рассылки. предполагается что имя может чуть поменяться со временем, но не номер

2021-04-15 07:49 UTC, realzuy commented on mymp/main/tasks.py
> +import main.models as model
согласен, но тут это не имеет смысла и только усложняет конструкцию, т.к. tasks в принципе предназначен для работы с задачами для всей модели модуля.

2021-04-15 07:49 UTC, realzuy commented on mymp/mymp/celery.py
> +        #'schedule': crontab(minute='*'),
ок, согласен

2021-04-17 23:15 UTC, morgangt approved these changes

2021-04-17 23:18 UTC, morgangt commented on mymp/main/tasks.py
> +import main.models as model
явное лучше не явное - дзен python. Если надо импортировать всю модель, то стоит изменить название модуля с просто model на что-то типо main_model 
`import main.models as main_model`

2021-04-18 11:57 UTC, merged